# Schema documented at https://render.com/docs/yaml-spec
services:
  - type: web # valid values: https://render.com/docs/yaml-spec#type
    region: ohio
    name: sample-service-name
    env: python # valid values: https://render.com/docs/yaml-spec#environment
    buildCommand: "./render_build.sh"
    startCommand: "gunicorn wsgi --chdir ./src/"
    plan: free # optional; defaults to starter
    numInstances: 1
    envVars:
      - key: VITE_BASENAME
        value: /
      - key: FLASK_APP
        value: src/app.py
      - key: FLASK_DEBUG
        value: "0"
      - key: FLASK_APP_KEY
        value: any_key_works
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: DATABASE_URL # Render PostgreSQL database
        fromDatabase:
          name: postgresql-trapezoidal-42170
          property: connectionString
      - key: JWT_SECRET_KEY
        value: tu_clave_super_secreta
      - key: SENDGRID_API_KEY
        value: tu_api_key_de_sendgrid

databases: # Render PostgreSQL database
  - name: postgresql-trapezoidal-42170
    region: ohio
    ipAllowList: [] # only allow internal connections
    plan: free # optional; defaults to starter
