"""add empresa model and new roles

Revision ID: 916188ced1e9
Revises: 7c0d1c9e7fbe
Create Date: 2025-12-05 17:02:50.631721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '916188ced1e9'
down_revision = '7c0d1c9e7fbe'
branch_labels = None
depends_on = None


def upgrade():
    # Crear tabla de empresas si no existe
    op.create_table(
        'empresas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre', sa.String(length=100), nullable=False),
        sa.Column('activo', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    # Eliminar token_blocklist solo si existe (para no romper despliegues antiguos)
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    if 'token_blocklist' in existing_tables:
        with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
            try:
                batch_op.drop_index(batch_op.f('ix_token_blocklist_jti'))
            except Exception:
                # Si el índice no existe, continuamos sin romper la migración
                pass
        op.drop_table('token_blocklist')

    # Añadir empresa_id a restaurantes y usuarios
    with op.batch_alter_table('restaurantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    # Ampliar el ENUM 'roles' existente para incluir super_admin y director
    op.execute("ALTER TYPE roles ADD VALUE IF NOT EXISTS 'super_admin'")
    op.execute("ALTER TYPE roles ADD VALUE IF NOT EXISTS 'director'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('restaurantes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('empresa_id')

    op.create_table('token_blocklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('token_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], name=op.f('token_blocklist_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blocklist_pkey'))
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blocklist_jti'), ['jti'], unique=True)

    op.drop_table('empresas')
    # ### end Alembic commands ###
